# FUTUREMODE 2026 workshop repo — attendee Makefile.
#
# This file is also a *marker*: labkit._find_repo_root() walks up from
# lab/labkit.py looking for a directory that has BOTH `poc/` and `Makefile`.
# Deleting this file breaks every artefact path in every notebook.
#
# Generated by scripts/export-workshop-repo.py in the upstream repo. The
# upstream Makefile drives the live AMD demos, which need hardware this export
# deliberately does not carry. What is here is the replay path, which needs
# nothing but Python.

PYTHON ?= python3
REPO_ROOT := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
JUPYTER := $(if $(wildcard $(REPO_ROOT)/.venv/bin/jupyter),$(REPO_ROOT)/.venv/bin/jupyter,jupyter)

.PHONY: help install replay replay-all lab verify clean

help:
	@echo "FUTUREMODE 2026 workshop repo — make targets:"
	@echo "  make install     # pip install -r lab/requirements.txt"
	@echo "  make verify      # check labkit imports and finds every artefact"
	@echo "  make replay      # replay the 6 curated notebooks (00/01/16/23/24/14)"
	@echo "  make replay-all  # replay all $(words $(wildcard $(REPO_ROOT)/lab/*.ipynb)) notebooks"
	@echo "  make lab         # start Jupyter Lab in lab/"
	@echo "  make clean       # drop checkpoint/pycache droppings"

install:
	$(PYTHON) -m pip install -r $(REPO_ROOT)/lab/requirements.txt

# Non-destructive: nbconvert writes executed copies into a temp dir and the
# source .ipynb sha256 is asserted unchanged. Never --inplace.
replay:
	bash $(REPO_ROOT)/run-replay.sh

replay-all:
	ALL=1 bash $(REPO_ROOT)/run-replay.sh

lab:
	cd $(REPO_ROOT)/lab && $(JUPYTER) lab

verify:
	$(PYTHON) $(REPO_ROOT)/verify-export.py

clean:
	rm -rf $(REPO_ROOT)/lab/.ipynb_checkpoints $(REPO_ROOT)/lab/__pycache__
